import pyautogui,time

pyautogui.click(x=535, y=363, clicks = 1)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')  
time.sleep(0.5)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.typewrite("De tal palo, tal astilla.")
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.hotkey('shift','2') #teclado ingles 
pyautogui.press('left')
time.sleep(0.5)
pyautogui.typewrite('WiFi-Botz-1')
time.sleep(0.5)
pyautogui.press('right')
time.sleep(0.5)
pyautogui.typewrite('gmail.com')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('enter')
#fin del script


#envio 2 
#pyautogui.click(x=652, y=247, clicks = 1)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('enter')

time.sleep(1)
pyautogui.click(x=535, y=363, clicks = 1)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')  
time.sleep(0.5)
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.typewrite("Quien tiene un amigo tiene un tesoro.")
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('enter')
pyautogui.press('down')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.hotkey('shift','2') #teclado ingles 
pyautogui.press('left')
time.sleep(0.5)
pyautogui.typewrite('WiFi-Botz-2')
time.sleep(0.5)
pyautogui.press('right')
time.sleep(0.5)
pyautogui.typewrite('outlook.es')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('enter')